"""agrego rol y activo a Usuario

Revision ID: 73fede52b5a6
Revises: 7b17060d9e48
Create Date: 2025-11-10 10:58:48.311801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fede52b5a6'
down_revision = '7b17060d9e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['password'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('activo')
        batch_op.drop_column('rol')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
