"""Creacion bd

Revision ID: 7b17060d9e48
Revises: bc1504059714
Create Date: 2025-08-26 12:13:02.998747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b17060d9e48'
down_revision = 'bc1504059714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('nombre'))

    op.drop_table('categoria')
    op.drop_table('post')
    op.drop_table('comentario')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('nombre_usuario'))

    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nombre_usuario'), ['nombre_usuario'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('comentario',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('texto', mysql.TEXT(), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('comentario_ibfk_1')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('comentario_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('contenido', mysql.TEXT(), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('post_ibfk_1')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('post_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categoria',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nombre'), ['nombre'], unique=True)

    # ### end Alembic commands ###
