"""Borro password de Usuario

Revision ID: d1aac6bbc812
Revises: a51d2b46f259
Create Date: 2025-11-11 11:21:30.247143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1aac6bbc812'
down_revision = 'a51d2b46f259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('password'))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
        batch_op.create_index(batch_op.f('password'), ['password'], unique=True)

    # ### end Alembic commands ###
